#resolver: lts-7.21

resolver: lts-3.22

packages:
- '.'
- location: 
    git: git@github.com:HaskellCNOrg/snaplet-mongodb-minimalistic.git
    commit: a8ce342e367b28ea87085308d5fddfc83c4df768
#https://github.com/HaskellCNOrg/snaplet-mongodb-minimalistic/archive/0.1.0.zip

#- compact-string-fix-0.3.2
#- digestive-functors-0.8.1.1
#- digestive-functors-heist-0.8.7.0
#- digestive-functors-snap-0.6.1.3
#- snap-loader-dynamic-0.10.0.4
#- snap-loader-static-0.9.0.2

extra-deps:
- compact-string-fix-0.3.2
- digestive-functors-heist-0.8.7.0
- digestive-functors-snap-0.7.0.0
- snap-loader-dynamic-1.0.0.0
- snap-loader-static-1.0.0.0
- snaplet-i18n-0.2.0
- snaplet-mongodb-minimalistic-0.1.0
